// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Proyecto_alcaldia.Infrastructure.Data;

#nullable disable

namespace Proyecto_alcaldia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260102143844_RefactorODSManyToManyMetasODS")]
    partial class RefactorODSManyToManyMetasODS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("EstadoActividad")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("estado_actividad");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFinProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_programada");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_real");

                    b.Property<DateTime?>("FechaInicioProgramada")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_programada");

                    b.Property<DateTime?>("FechaInicioReal")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio_real");

                    b.Property<decimal?>("MetaPlaneada")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("meta_planeada");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PorcentajeAvance")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_avance");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.Property<decimal?>("PresupuestoEjecutado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_ejecutado");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("responsable_id");

                    b.Property<string>("TipoActividad")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_actividad");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("unidad_medida");

                    b.Property<int?>("VigenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_id");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("VigenciaId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("actividades");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcalde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_electronico");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("numero_documento");

                    b.Property<string>("PartidoPolitico")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("partido_politico");

                    b.Property<DateTime?>("PeriodoFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_fin");

                    b.Property<DateTime?>("PeriodoInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_inicio");

                    b.Property<string>("Slogan")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("slogan");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("alcaldes");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.AlcaldeVigencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AlcaldeId")
                        .HasColumnType("integer")
                        .HasColumnName("alcalde_id");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VigenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_id");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaId");

                    b.HasIndex("AlcaldeId", "VigenciaId")
                        .IsUnique();

                    b.ToTable("alcaldes_vigencias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcaldia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int?>("AlcaldeActualId")
                        .HasColumnType("integer")
                        .HasColumnName("alcalde_actual_id");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_institucional");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("integer")
                        .HasColumnName("departamento_id");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Logo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logo");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nit");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.ToTable("alcaldias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("departamentos");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("integer")
                        .HasColumnName("actividad_id");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaEvidencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evidencia");

                    b.Property<string>("HashArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_archivo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreArchivo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_archivo");

                    b.Property<string>("RutaAlmacenamiento")
                        .HasColumnType("text")
                        .HasColumnName("ruta_almacenamiento");

                    b.Property<long?>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoEvidencia")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_evidencia");

                    b.Property<string>("TipoMime")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_mime");

                    b.Property<string>("URLPublica")
                        .HasColumnType("text")
                        .HasColumnName("url_publica");

                    b.Property<string>("UbicacionCaptura")
                        .HasColumnType("text")
                        .HasColumnName("ubicacion_captura");

                    b.Property<int?>("Verificada")
                        .HasColumnType("integer")
                        .HasColumnName("verificada");

                    b.Property<int?>("VerificadaPor")
                        .HasColumnType("integer")
                        .HasColumnName("verificada_por");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("VerificadaPor");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("evidencias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Indicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("LineaBase")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("linea_base");

                    b.Property<decimal?>("MetaFinal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("meta_final");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("responsable_id");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("indicadores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.LineaEstrategica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PlanDtpId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_dtp_id");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("lineas_estrategicas");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.MetaODS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("metas_ods");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("municipios");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ODS", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("NivelImpacto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nivel_impacto");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("ods");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ODSMetaODS", b =>
                {
                    b.Property<int>("ODSId")
                        .HasColumnType("integer")
                        .HasColumnName("ods_id");

                    b.Property<int>("MetaODSId")
                        .HasColumnType("integer")
                        .HasColumnName("meta_ods_id");

                    b.Property<DateTime>("FechaAsociacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asociacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("ODSId", "MetaODSId");

                    b.HasIndex("MetaODSId");

                    b.ToTable("ods_metas_ods");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanDepartamental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Eje")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("eje");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("planes_departamentales");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanMunicipal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("AlcaldeId")
                        .HasColumnType("integer")
                        .HasColumnName("alcalde_id");

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<int?>("MunicipioId")
                        .HasColumnType("integer")
                        .HasColumnName("municipio_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("PlanDptlId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_dptl_id");

                    b.Property<int?>("PlanNacionalId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_nacional_id");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldeId");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("PlanDptlId");

                    b.HasIndex("PlanNacionalId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("planes_municipales");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanNacional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Eje")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("eje");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("planes_nacionales");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("integer")
                        .HasColumnName("programa_id");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("productos");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("MetaResultado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("meta_resultado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int?>("ODSId")
                        .HasColumnType("integer")
                        .HasColumnName("ods_id");

                    b.Property<int?>("PlanMunicipalId")
                        .HasColumnType("integer")
                        .HasColumnName("plan_municipal_id");

                    b.Property<decimal?>("PresupuestoCuatrienio")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_cuatrienio");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.HasKey("Id");

                    b.HasIndex("ODSId");

                    b.HasIndex("PlanMunicipalId");

                    b.HasIndex("SectorId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("programas");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<decimal?>("CodigoBPIN")
                        .HasColumnType("numeric(18,0)")
                        .HasColumnName("codigo_bpin");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("EstadoProyecto")
                        .HasColumnType("boolean")
                        .HasColumnName("estado_proyecto");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PorcentajeAvance")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_avance");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.Property<decimal?>("PresupuestoEjecutado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_ejecutado");

                    b.Property<int?>("ResponsableId")
                        .HasColumnType("integer")
                        .HasColumnName("responsable_id");

                    b.Property<decimal?>("ValorProyecto")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor_proyecto");

                    b.HasKey("Id");

                    b.HasIndex("ResponsableId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ProyectoIndicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("IndicadorId")
                        .HasColumnType("integer")
                        .HasColumnName("indicador_id");

                    b.Property<decimal?>("PorcentajeAvance")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_avance");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("integer")
                        .HasColumnName("proyecto_id");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId");

                    b.HasIndex("IndicadorId");

                    b.HasIndex("ProyectoId", "IndicadorId")
                        .IsUnique();

                    b.ToTable("proyectos_indicadores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Responsable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_identificacion");

                    b.Property<int?>("SecretariaId")
                        .HasColumnType("integer")
                        .HasColumnName("secretaria_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_documento");

                    b.Property<string>("TipoResponsable")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_responsable");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("SecretariaId");

                    b.ToTable("responsables");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Secretaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo_institucional");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.Property<string>("Secretario")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("secretario");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sigla");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("secretarias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Aplicacion")
                        .HasColumnType("text")
                        .HasColumnName("aplicacion");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LineaEstrategicaId")
                        .HasColumnType("integer")
                        .HasColumnName("linea_estrategica_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.HasKey("Id");

                    b.HasIndex("LineaEstrategicaId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("sectores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Subsecretaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("CorreoInstitucional")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correo_institucional");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal?>("PresupuestoAsignado")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_asignado");

                    b.Property<string>("Responsable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsable");

                    b.Property<int>("SecretariaId")
                        .HasColumnType("integer")
                        .HasColumnName("secretaria_id");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("SecretariaId");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("subsecretarias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correo_electronico");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("FotoPerfilEncriptada")
                        .HasColumnType("text")
                        .HasColumnName("foto_perfil_encriptada");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("TemaColor")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tema_color");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("CorreoElectronico")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_asignacion")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("RolId")
                        .HasColumnType("integer")
                        .HasColumnName("rol_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId", "RolId")
                        .IsUnique();

                    b.ToTable("usuarios_roles");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Vigencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<int>("AlcaldiaId")
                        .HasColumnType("integer")
                        .HasColumnName("alcaldia_id");

                    b.Property<int>("Año")
                        .HasColumnType("integer")
                        .HasColumnName("año");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("AlcaldiaId", "Codigo")
                        .IsUnique();

                    b.ToTable("vigencias");
                });

            modelBuilder.Entity("municipio_departamentos", b =>
                {
                    b.Property<int>("municipio_id")
                        .HasColumnType("integer");

                    b.Property<int>("departamento_id")
                        .HasColumnType("integer");

                    b.HasKey("municipio_id", "departamento_id");

                    b.HasIndex("departamento_id");

                    b.ToTable("municipio_departamentos", (string)null);
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("Actividades")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Vigencia", "Vigencia")
                        .WithMany()
                        .HasForeignKey("VigenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Proyecto");

                    b.Navigation("Responsable");

                    b.Navigation("Vigencia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcalde", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany("Alcaldes")
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.AlcaldeVigencia", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcalde", "Alcalde")
                        .WithMany("AlcaldesVigencias")
                        .HasForeignKey("AlcaldeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Vigencia", "Vigencia")
                        .WithMany("AlcaldesVigencias")
                        .HasForeignKey("VigenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alcalde");

                    b.Navigation("Vigencia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcaldia", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Alcaldias")
                        .HasForeignKey("DepartamentoId");

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Municipio", "Municipio")
                        .WithMany("Alcaldias")
                        .HasForeignKey("MunicipioId");

                    b.Navigation("Departamento");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Evidencia", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Actividad", "Actividad")
                        .WithMany("Evidencias")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Usuario", "VerificadaPorUsuario")
                        .WithMany()
                        .HasForeignKey("VerificadaPor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Actividad");

                    b.Navigation("Alcaldia");

                    b.Navigation("VerificadaPorUsuario");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Indicador", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Producto", "Producto")
                        .WithMany("Indicadores")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Producto");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.LineaEstrategica", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.MetaODS", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ODS", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ODSMetaODS", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.MetaODS", "MetaODS")
                        .WithMany("ODSMetasODS")
                        .HasForeignKey("MetaODSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.ODS", "ODS")
                        .WithMany("ODSMetasODS")
                        .HasForeignKey("ODSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetaODS");

                    b.Navigation("ODS");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanDepartamental", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Sector", "Sector")
                        .WithMany("PlanesDepartamentales")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanMunicipal", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcalde", "Alcalde")
                        .WithMany()
                        .HasForeignKey("AlcaldeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.PlanDepartamental", "PlanDepartamental")
                        .WithMany("PlanesMunicipales")
                        .HasForeignKey("PlanDptlId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.PlanNacional", "PlanNacional")
                        .WithMany("PlanesMunicipales")
                        .HasForeignKey("PlanNacionalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcalde");

                    b.Navigation("Alcaldia");

                    b.Navigation("Municipio");

                    b.Navigation("PlanDepartamental");

                    b.Navigation("PlanNacional");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanNacional", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Sector", "Sector")
                        .WithMany("PlanesNacionales")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Producto", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Programa", "Programa")
                        .WithMany("Productos")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Programa", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.ODS", "ODS")
                        .WithMany("Programas")
                        .HasForeignKey("ODSId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.PlanMunicipal", "PlanMunicipal")
                        .WithMany("Programas")
                        .HasForeignKey("PlanMunicipalId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Sector", "Sector")
                        .WithMany("Programas")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");

                    b.Navigation("ODS");

                    b.Navigation("PlanMunicipal");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Proyecto", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Responsable", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ProyectoIndicador", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Indicador", "Indicador")
                        .WithMany("ProyectosIndicadores")
                        .HasForeignKey("IndicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Proyecto", "Proyecto")
                        .WithMany("ProyectosIndicadores")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alcaldia");

                    b.Navigation("Indicador");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Responsable", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany("Responsables")
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Responsables")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Alcaldia");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Secretaria", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany("Secretarias")
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Sector", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany()
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.LineaEstrategica", "LineaEstrategica")
                        .WithMany("Sectores")
                        .HasForeignKey("LineaEstrategicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");

                    b.Navigation("LineaEstrategica");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Subsecretaria", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany("Subsecretarias")
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Secretaria", "Secretaria")
                        .WithMany("Subsecretarias")
                        .HasForeignKey("SecretariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");

                    b.Navigation("Secretaria");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuariosRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Vigencia", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Alcaldia", "Alcaldia")
                        .WithMany("Vigencias")
                        .HasForeignKey("AlcaldiaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alcaldia");
                });

            modelBuilder.Entity("municipio_departamentos", b =>
                {
                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Departamento", null)
                        .WithMany()
                        .HasForeignKey("departamento_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_alcaldia.Domain.Entities.Municipio", null)
                        .WithMany()
                        .HasForeignKey("municipio_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcalde", b =>
                {
                    b.Navigation("AlcaldesVigencias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Alcaldia", b =>
                {
                    b.Navigation("Alcaldes");

                    b.Navigation("Responsables");

                    b.Navigation("Secretarias");

                    b.Navigation("Subsecretarias");

                    b.Navigation("Vigencias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Alcaldias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Indicador", b =>
                {
                    b.Navigation("ProyectosIndicadores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.LineaEstrategica", b =>
                {
                    b.Navigation("Sectores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.MetaODS", b =>
                {
                    b.Navigation("ODSMetasODS");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Municipio", b =>
                {
                    b.Navigation("Alcaldias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.ODS", b =>
                {
                    b.Navigation("ODSMetasODS");

                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanDepartamental", b =>
                {
                    b.Navigation("PlanesMunicipales");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanMunicipal", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.PlanNacional", b =>
                {
                    b.Navigation("PlanesMunicipales");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Producto", b =>
                {
                    b.Navigation("Indicadores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Proyecto", b =>
                {
                    b.Navigation("Actividades");

                    b.Navigation("ProyectosIndicadores");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Rol", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Secretaria", b =>
                {
                    b.Navigation("Responsables");

                    b.Navigation("Subsecretarias");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Sector", b =>
                {
                    b.Navigation("PlanesDepartamentales");

                    b.Navigation("PlanesNacionales");

                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuariosRoles");
                });

            modelBuilder.Entity("Proyecto_alcaldia.Domain.Entities.Vigencia", b =>
                {
                    b.Navigation("AlcaldesVigencias");
                });
#pragma warning restore 612, 618
        }
    }
}
